version: '3'
services:
  db:
    image: "postgres:12.2"
    restart: always
    env_file:
      - src/.env
    ports:
      - '5432:5432'
    volumes:
      - rubyfunctions_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  web:
    build: src/
    entrypoint: /app/scripts/entrypoint.sh
    volumes:
      - ./src/:/app
    depends_on:
      - db
    links:
      - db
    restart: always
    ports:
      - '127.0.0.1:9000:3000'
    env_file:
      - src/.env
volumes: 
  rubyfunctions_db: