version: '3'
services:
  db:
    image: "postgres:12.2"
    restart: always
    env_file:
      - src/.env
    expose:
      - '5432'
    volumes:
      - rubyfunctions_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: src/
      dockerfile: Dockerfile-dev
    volumes:
      - ./src/:/app
      - gems:/gems
    depends_on:
      - db
    links:
      - db
    restart: always
    ports:
      - 3000:3000
    env_file:
      - src/.env
volumes:
  rubyfunctions_db:
  gems:
