FROM ruby:2.6.3-slim
ENV LANG=C.UTF-8
RUN apt update && apt install -qq -y build-essential nodejs libpq-dev postgresql-client npm --fix-missing --no-install-recommends
RUN gem install bundler
RUN npm install --global yarn

ENV app /app
RUN mkdir -p $app
WORKDIR $app

ENV BUNDLE_PATH /gems
