source 'https://rubygems.org'

ruby '~>2.6.3'

gem 'rails', '~> 6.0.0'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'pg'
gem 'puma', '~> 4.3'
gem 'rest-client'
gem 'rouge'
gem 'sass-rails', '~> 6'
gem 'webpacker', '~> 5.0'

group :development, :test do
  gem 'factory_bot_rails'
  gem 'pry-rails'
  gem 'rspec-rails'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.3'
  gem 'rubocop-rails', require: false
end

group :test do
  gem 'faker'
  gem 'shoulda-matchers'
end

group :production do
  gem 'sentry-raven'
end
